import { Customer } from "./customer";
import { OrderItem } from "./OrderItem";

export class Order {
  order_uuid:string;
  payment_uuid:string;
  customer_id:string;
  customer_name:string;
  customer_phone_number:string;
  customer_phone_country_code:string;
  customer_email:string;
  restaurant_uuid:string;
  area_id:number;
  area_name:string;
  area_name_ar:string;
  unit_type:string;
  block:string;
  street:string;
  avenue:string;
  house_number: string;
  delivery_zone_id:number;
  shipping_country_id:number;
  country_name:string;
  country_name_ar:string;
  business_location_name:string;
  floor:string;
  apartment:string;
  building:string;
  office:string;
  city:string;
  postalcode:string;
  address_1:string;
  address_2:string;
  special_directions:string;
  payment_method_id:number;
  payment_method_name:string;
  payment_method_name_ar:string;
  currency_code: string;
  currency_rate: number;
  total_price:number;
  subtotal:number;
  subtotal_before_refund:number;
  total_price_before_refund:number;
  delivery_fee:number;
  order_status:number;
  order_mode:number;
  estimated_time_of_arrival:string;
  delivery_time:number;
  order_created_at:string;
  order_updated_at:string;
  restaurant_branch_id:number;
  armada_tracking_link:string;
  items_has_been_restocked:number;
  latitude:number;
  longitude:number;
  is_order_scheduled:number;
  scheduled_time_start_from:string;
  scheduled_time_to:string;
  armada_qr_code_link:string;
  voucher_id:number;
  voucher_discount: number;
  armada_delivery_code:string;
  mashkor_order_number:string;
  mashkor_tracking_link:string;
  mashkor_driver_name:string;
  mashkor_driver_phone:string;
  mashkor_order_status:number;
  bank_discount_id:number;
  reminder_sent:number;
  sms_sent:number;
  pickup_location_id:number;
  tax:number;
  recipient_name:string;
  recipient_phone_number:string;
  gift_message:string;
  area:any;
  customer: Customer;
  orderItems: OrderItem[];
}
